# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMilestone3US1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path='/mnt/c/chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_milestone3US1(self):
    self.driver.get("http://localhost:5002/")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-times").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-map-marker").click()
    self.driver.find_element(By.ID, "map").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
  
